version: "3.1"
services:
  nestjs-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node_app_container
    # image: a7medabdo6/care_managment
    volumes:
      - ./backend/src:/App/src:ro
    ports:
      - "5000:5000"

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    # volumes:
    #     - ./Care_Frontend/build:/usr/share/nginx/html:ro
    ports:
      - 82:82
    restart: always
